### ISSUE TITLE
Bug in my log

### ISSUE THREAD

**Issue by heiler** [vesta-webtrees-2-custom-modules/vesta_common#104]
I tried different themes.

```
…/modules_v4/vesta_gov4webtrees/resources/css/style.css"))) AND ((("NlGV" LIKE "NlGV …/modules_v4/vesta_common/VestaModuleTrait.php:360
#0 …/app/Http/RequestHandlers/ModuleAction.php(85): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule->getAssetAction()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#1 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#3 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#5 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_personal_facts#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#8 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#9 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#11 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_common#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#13 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#15 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_shared_places#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
vesta-webtrees-2-custom-modules/vesta_shared_places#24 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#19 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#20 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#21 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#23 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#25 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#27 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#29 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#31 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#33 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#35 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#37 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#39 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#41 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#43 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_shared_places#77 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#46 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#48 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#50 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#52 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#54 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#57 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#58 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#59 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
vesta-webtrees-2-custom-modules/vesta_gov4webtrees#60 {main}
```

**Comment by ric2016** [comment]
Fixed in commit.

Vesta used outdates webtrees files - If those were still available from previous webtrees versions, this resulted in the reported error.

Now handled properly, without logging an error:

<img width="857" alt="404" src="https://user-images.githubusercontent.com/18174787/231284482-637cbcc5-c797-4dc2-a3b7-7a3b2130ace9.PNG">
