### ISSUE TITLE
Error when I try to add a related person to a family (FAM:ASSO)

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_common#67]
```
Fisharebest\Webtrees\Services\RelationshipService::getCloseRelationshipName(): Argument #2 ($individual2) must be of type Fisharebest\Webtrees\Individual, Cissee\WebtreesExt\FamilyExt given, called in …/modules_v4/vesta_common/resources/views/fact.phtml on line 208 …/app/Services/RelationshipService.php:75
#0 …/modules_v4/vesta_common/resources/views/fact.phtml(208): Fisharebest\Webtrees\Services\RelationshipService->getCloseRelationshipName()
#1 …/app/View.php(183): include('...')
#2 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#3 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#4 …/modules_v4/vesta_personal_facts/resources/views/family-page.phtml(105): view()
#5 …/app/View.php(183): include('...')
#6 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#7 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
```

**Comment by ric2016** [comment]
Fixed in latest release 2.1.2.0.0.
